name: Werbung
version: '1.0-SNAPSHOT'
main: ch.powercraft.werbung.Werbung
api-version: '1.20'
commands:
  werbung:
    permission: lythia.werbung
    permission-message: "§c§lʟʏᴛʜɪᴀ §8| §cDu hast keine Rechte um die Werbung zu schalten§8"